### ISSUE TITLE
Can you help me parse this string?

### ISSUE THREAD

**Issue by smj199265** [Ciphey/Ciphey#761] opened 2022-12-07 14:01 UTC
I can't use my Mac without a doctor. I want to see what encryption methods are available. Thank you very much
"44PN44PNCTWlYm7zvWUzzX/ytMeycWobgYwazbGwtVV8LaViChBNtBv/zrF4tBvuwBF4v+rCernMzh+8wBnptBv/xrnLe+zHtBJHehnKhhJgb++8wBnVxrJ3fhr7w+v/ahr7erJAvhF4dhnpvBnlbrnpvGRk54X55LzA5Mhr6Y+U5n625YdT44PP5nJ95YvA5n655cvG6X6v5L2I6LrC57lG5YvY5c2y77lZ54z55Lve5cvi5bvE5Mhr5n626Yri5YvX55dR6Yri54Ti6Y+L5M2C5YdT77lZ5bvE5clW5bFC6X+T5olN5nrY5LrT5nFU5d+C5nFc5crc54X55Mhr5n6244PPCTWlYm7wtVQzaVQbi5UiiVmzvWUyw5UaweQzaVaxheeyaXwbg5/bhXezvWUwtVV8LaViChBNtBv/ahr7erJyirJUbBJxdrzQirnLe+v/zrntg++8wBnVxrnMzhF4vhJqxBJpfBzGtrJoahJhghrnuBnKghJNzrF8zhF4tBnhgrv3e+BNthniw+nfbrF4tBv/u+JAtrJgy+v3e+JCb++8wBnVxrJjfrF8zhJCxrrBfBvQwBJDwhJxzhF6uhF4cBF4dhJ9frJgxBBNtwkvpv8+44PN5Lvn5olN5nrY77lZ5bvE5Yhy5Yv65L+d5cvi6nT66Yri5YvY54+g44PO5MPZ5Y2C5YvN5Yvd5oPC5Ll655dR5Yd677lZ5Y2T5cvi5evD5evD55dR5bvE5L+E546j5YdY5bBS5oz25YvA5n+55Ldl77lZ5d+C5dlu5bvE6YJj5Lvj5oPC5Ll65Y+q5n6W5Ydg55dR5cr25LPM77lZ5YhJ5Yhf5oPk5Yln5b6W5nF056n75olN44PPCTWlYm7wtVQxh5oxh6mxhV3zzX/xiL/yaXwbi5acu4miiVmxh5oxh6myw6ezzX/bg5/bhXeyfY7czb/zvWUzanKiiVmabn7bedGzvWUxiL/yaXwbi5axhXeyfV/ywYewtVV8LaViChBNtBvNwBnVxrnLe+F4dhJ5gBv9h+Jyf+F6hh+8wBrYeBJkur+8wBnHghJScrF4wrvCfhBNtwkvpv8+44PN6Y+M5Yvd5YdY5bBS5YvN6X+06Y+L5o6V5bTD5bPJ77lZ6nXU5clW54X56LB95ovP5nJU6YPV55dR5bFs6XrW44PPCTWlYm7wtVQxiLozzX/yco3yaXwzvWUxiL/azbGbi5axhXeyfV/ywYeavnaaedUcaM7yhYwyvYQxiL3iiVmyiMCzvWUzvbexhbizt4Kbg5/xi53yebazw4/bi7QxhboxhVQxhViyw4wctVUxhboyu6QywVKat5/xhLiyxV7iiVmxi53yebaycXsyx6KyfYUxi6UbdcCzy6ozy6oyaYQzvbebi5axhXexhbizt4Kzw73yaXwxhboxh5obhdixhVewtVV8LaViChBNtBnWtBF7crrfeBF6wBJxdrJ9x+nVxrJpdBJDwBntg+rnuBnKghzKgBv1fBJVfBJjw+JZhhzKdBJCb++8wBvQwBJDwhF4wrv/aBF4wrv/xrv3a+rqtBrnuBzPb+F4cBF4dhF6hhv/zBviyrJoihv3a+rqtBnVxrJ+tBJjw+JZhhzUwBv1fBrnuBnKghJNzr+8wBF/arJhvrJxc+JGcrF7eBrhtBrogBJzthrZz+vMwhJUhhJkfr+8wBF4vrF4cBngcrJjfrrdaBF4vhJBh+nXvhF6hhzNehF6uhBNtwkvpv8+44PN4bPp5MnP77lZ5bvE556S5Y2t5Yhf5nJ95Lrt5nFc5YdT77lO4bPqCTWlYm7wtVQbi5axhXGxheexhV3cuL3yxVwiiVmbi5wzt7Cbg5UwtVV8LaViChBNtBF/arJhvrJxc+JGcrF7eBJKx+zKdBJxc++8wBJxc+JwfBF4tBzdthv/ahv3e+rOe+F4vhrnuBrOfBzQirzpu+F4v+nqcr+8zhXNaBF4tBJxdrJxdrrnuBJjfrF8zhv3a+v4dhJjw+JaxrJbzB+8wBnpvrF7tBF5vBviarv3a+nVxrJBh+JktBJgxBzUwBzqbhvigBJDc++8trXNaGkvpv8+44PN4bPp5L2a5dr977lO6Y+L5Ldb5bzY77lO5bdy6X2z77lO5o+e5bdy6X2z77lO77lO4bPqCTWlYm7wtVQbi5axhXeyfV/ywYeyaYQaxVoxiL3ain7yco3iiVmxhV3bi5myfYUzzX/bbMsctMCzgY7yu7ezvLQiiVmbin7ytYmazbGbenoye5/yw5Gyw5GzwdKyvYQayYKbe53yu7ebenoct73zzX/zenKbbLmzanKazbGwtVV8LaViChBNtBXNaBv/zrJCd+F7tBF5vB+8a+v/zrJCd+vNtrvMwhJxgBF4vhnYyBniz+BNthXNarF/arJhvrJxc+JGcrnAthrqtBvRhBF5vrnRcBJud+vThhJpfBzdth+8wBXNaBznyBJwtrzPb+vuy+JjfrnLe+rWu+JRi+nWtB+8wBF9bBF7eBv/zBnIbhnDahJjihznw+v/zrJyy++8trvQuhJgxBJxc+JIvh+8trXNaGkvpv8+44PN6X2z5n+s5L+H5L+H5o6V5Yvy6VXQ77ln4bPp5Lve5Md35Md377lZ5nJ95nJ96X6l5YdY5bBS57hC6Y+U77lZ5LTn56lH5o2I5MTv44PP4bPqCTWlYm7wtVQzvWUxhM/bwnCyhowyaYQbi5iyfLQyeMQbg5/xi53yebaycXsyx6KyxVmyaMQiiVmbc4Gbc4Gaa6aaa6ayaYQcuL3yxVwzgLUadViwtVV8LaViChBNtBJDwBnKghnVxrF5a+rfeBF4tBnfbrrpv+n4urnyzhF6uhv/zrF4cBF6hhrnuBntg+JgxBBNtwkvpv8+44PN5YhJ5Yhf5oz25YvA5cvi5bvE5bBm6YTu5Yvg56z35Lr25c6O5bT255dR56F+5Yln6M2F5oz077lZ5L+A6VPZ5cvi5n+55Lnp5c2E55dR5Yvg5oz05nFe5nnU77lZ55lY6YJ35c2y57hC5eJB5bBS5Ln15YvA5nJ955dR6LXw56rA44PP55F355dR56z/552N6VPO5olC55dR56Th6Vzi5ovQ5cnM6XTf6XTe77lZ5Yd66LPt6M2c55dh6M6Y5orl57hC6VFk5oTE5YdT77lo5nJm5Yd66Yde5c2D6VrQ6VX/6VPZ55dh6VXx57XK57BM5cdK6ohR77lZ55lY6YJ35c2y5c6O6VPO44PPCTWlYm7wtVQbi5axhXGxheeyg7Yah4/ah5azv7szzcozfWGavLsxhVeiiVmbtYsaaVaaa4YaaYmiiVmxhV3zynYzvdmycYGwtVV8LaViChBNtBXNaBF9bBF7eBF/drJxc+JAvhJxaBv3a+rqtBF6hhJjw+JaxrJbzBJ5fhJIcr+8a+XNarvgchJia+JCyBJCyBzKehviar+8wBXNaBF6hhJhghF/arJhvrzKehviar+8wBF9bBv/zBnWx+F6hh+8a+XNaGkvpv8+44PN6Y+M5nFe5nn75cFi5cFi5MP+5MP+77lZ5L2X5nFc6X+05YvA5evS5dJn6X+q44PPCTWlYm7wtVQvtWmxh5oxh6mbg5/bhXebi5axiL3yfV/yc5Qyco3yu6QycXaxhboiiVmxhV3aa6KctMCzzX/zvMCaaLQxh4QxhLwxhYizuV/iiVmvtW3xi53yebayzVQyxcKiiVmvtWmyvXizzX/xheebgXayeMQyxXsvtXovtXovtW08LaViChBNtBv/zrviarJQw+nLe+F4dhJ8tBJSf++8wBF4erJ5gBJzu+Jyf+rZz+rnuBnXeBv1g+JxgBnqcrBNtwkvpv8+44PN4bPp54vk5nvw77lO4bPq5nJ55nFa5MBg77lZ4bPp5bvE5cvi5Y2t5nnV5nnV77lO5bvE5cvi5Y2t5Ydl5nnV5nnV5MJX77lO77lO4bPqCTWlYm7wtVQbi5abe53xhVQyu7eiiVmycXsyeeoazbGaaYmyuLact73aaViyxWUzvWUxhbowtVV8LaViChBNtBnVxrF5a+J+vBvZd+rRgh+8wBJ+vBr6f+zKg++8wBrogBnBcrnYi+JUhhv6d+F7irvitr+8zhXNaBnVxrJCd+Jhv+zour+8wBnVxrJhwBJSdBF4wrvhcBviuhF7yhF7eBJIvhBNthXNaGkvpv8+44PN6X2z5n+s5b6y6Y+U5bvE6Yde5Yh96X+O5YvN55lY77lZ56Th5n6r5cvi5nnP5d2x77lZ5bzN5Yhy5LnA6M2v5n+55Yvg5oz05nFe5nnU55dR5cr25LPM6X+g5ePH5oPk5Yvy5L6W6YJ35c2y5YdT77ln4bPp5bvE546j5Mlb5cvi5Y6Y6XTZ6Mrh6X+q77lO5Y2t5Yhf5nFa5L2X5nFp6Yrs6Yvd5Yd65n625orl57hC5cvi6Y+q5L+A5eX75n6W5c2u5Y6Y5YdT77lZ5L+i5Yhy5bhL55JM55dR77lO5LnA5ehu5Mv06YrE54Te6Y2z4bPH4bPH4bPqCTWlYm7wtVQyw6/zzX/bi5axhX3yhoGycbsycoCyi73auYoad5abgoszanKiiVmyxceyxceyaYQayXwycYGzxc7ybcaiiVmyu4GywbayaYQycXsyybeiiWevtWmavYUydXCiiVUavYUydXCiiVUycbwycbwye7axhV3bgosxinQiiVUycbwycbwzvbexinQaaVixhXYxhboiiVUavYUydXCiiVmzvWUaaW/azbGzzX/xinQycbwycbwiiVmzvWUaaW/azbGzzX/xinQycbwycbwyyLeiiVUvtW08LaViChBNtBJphhzqbhF5frF6uh+8wBJxc+JhghF8zrr6g+r6g+JBh+nYvrrqtBJyhrF4wrvhdrJyhrJCxrrJe+BNtwkvpv8+44PN5bvE5M2D5Mlb6LXw6LrZ77lZ5o275odI5br16LP85YdT44PPCTWlYm7wtVQyuooyec7zvWUabn7yec7zzX/xhXeyenGyuY/iiVmxiLozzX/ctdCzzX/bi4syweiazbGxhbizt4KxhboiiWizvWUzzV7abn7aa6KctMCzvWUzzX/bbdiaweQyaXwazbGavYoze43zyYoyuoiazbGwtVV8LaViChBNtBnVxrrnuBJSh+rVghniwrF5a+J+vBn4urnyzhJpfBJDxrnVxrvigBF6uhv/zrF4dhF6v+nQur+8wBJ5ghnlbrnpvrF7h+F9yrznxBrrxhBNtwkvpv8+44PN5YhJ5Yhf5cF25LJ75bvE55dR6LXw5Yvd5cr25LPM77lZ5bvE5n6r5Mlb5cvi5nFd5oPC5YdT77lZ5bzA5Yvx5YvW5oXO44PPCTWlYm7wtVQctdCzy7oytWazvWUazbGyuoiavYoyuoize43ct73zzX/cd5wahdsaa6Kbe4oyvVoyeMQiiVmxh5oxh6mzaVaxhVQxhXeycXsyuY/yeMQiiVmyxbmxhVQxhXeycX3zvcwazbGyfV/ycoCyuY/wtVYxh5oxh6mazbGycoCyuY/yxbmzvWUxhVQzbYsycXswtVV8LaViChBNtBrBfBJpdBnVxrJSh+rVghvigBv1g+v/zrF4dhJjw+Jyf+JRi+zQirF8zhJ/wrF4wrF9w+n1trnmdh+8wBF7yhvigBzPb+nKghJNzrF7yhF7eBnkthJXdrF6uhJoirJTurJxyhF4tBJVu+vQirJxa+J+y+F4vhrnuBJZh+rJy+nphhnruB+8wBF9uhnLe+v/zBnLe+nlbrnpvrrIzrF9w+v/zrF4dhJjw+JxdrF9i+BNthJ5hhJyf+rnuBF4wrJ5hBJxernXzBnLe+JihrJhghJ6errnuBJ3dBJxc+nWx+JUh++8wBnVxrrnuBJSh+niwrzQtrzQtrJibrnfbh+8wBF4tBJ6chJ0drn6t++8wBF4hhF6uhF9i+nVxrrnuBJSh+niwrJyirv9eB+8wBnVxrrnuBJSh+rVghnHghJSh+F6uhnVxrBNtwkvpv8+44PN5Y2T5cvi5bvE55dR5LJ754v26X+05YhJ5cvi5YhB5d2w6XrR6LPH5o6R5cF25LJ755dR77lZ5cvi5YvN5Yvd56F+5Yln56nC5Lvc6Mzv77lZ5bzY57hg6o2D5LJb77lo5Y2T5LJ25n6r5YhJ5Yzs5oz25YvA55+y6LTG5bvE5cvi5YhB5MBd6LrZ5c2y55dR77lZ56nC5Lvc6Mzv5Yzs5YvA5evS5dJn5bvE55dR54v25d+A5Yv65YhN5YzV5bdo5olQ5bvE44PPCTWlYm7wtVQztYixhLiiiVmzvWUyfYUzanKyvYQxhboaweQyaXwazbGyeeoyhd3wtVV="

**Comment by SkeletalDemise** [comment] 2022-12-29 16:59
Closing this because it's not a bug. You can ask for help with specific ciphertexts in our Discord channel #coded-messages.
https://discord.gg/MfuMzEVjtK

**Closed by SkeletalDemise** 2022-12-29 16:59 UTC
