### ISSUE TITLE
ciphey is Thinking...  invariably！

### ISSUE THREAD

**Issue by lijiachang** [Ciphey/Ciphey#743] opened 2022-06-22 04:58 UTC
#ciphey -t "mbelL81o2jJS+YaPpypB2Q=="
ð  Thinking...

If he can't guess the plaintext, won't he quit?

**Comment by gwo0d** [comment] 2022-10-01 16:53
Hi all!

I've been able to replicate this issue, so I'm going to look into this and try to identify the cause. If I find it, I'll submit a patch via PR in the next couple of days.

Best!

**Comment by SkeletalDemise** [comment] 2022-11-26 08:34
Closing because this isn't a bug. If Ciphey is thinking for a long time then that usually means it can't crack your ciphertext.
Ciphey will run infinitely trying more and more obscure combinations.

**Closed by SkeletalDemise** 2022-11-26 08:34 UTC
Labels: bug
