### ISSUE TITLE
"string index out of range" for -t Flag

### ISSUE THREAD

**Issue by LPoeppel** [Ciphey/Ciphey#713] opened 2021-11-21 18:59 UTC
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [ Yes ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
String out of range.

**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: [e.g. Windows, Debian 11.0, Arch, OS X El Capitan]
 Any. Found on Debian/Kali (5.14.0-kali4-amd64)
 - Python version: [python3 --version]
 3.9.8 
 - Ciphey versions: [python3 -m pip show ciphey cipheycore cipheydists]
 Name: ciphey
Version: 5.14.0
Summary: Automated Decryption Tool
Home-page: None
Author: Brandon
Author-email: brandon@skerritt.blog
License: MIT
Location: /home/username/.local/lib/python3.9/site-packages
Requires: base91, mock, pybase62, pywhat, cipheydists, base58, flake8, click, pyyaml, appdirs, pylint, rich, loguru, cipheycore
Required-by: 
---
Name: cipheycore
Version: 0.3.2
Summary: 
Home-page: None
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License: None
Location: /home/username/.local/lib/python3.9/site-packages
Requires: 
Required-by: ciphey
---
Name: cipheydists
Version: 0.3.35
Summary: A collection of distributions, character sets and dictionaries for use in ciphey
Home-page: None
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License: None
Location: /home/username/.local/lib/python3.9/site-packages
Requires: 
Required-by: ciphey
 - Did you use Docker? No

**To Reproduce**
1) $: ciphey -t "56inrkS7AcAXatqrFM"
2) -t

**Expected behavior**
Solving the string.

**Any other information?**
Debug error:
ciphey -t "56inrkS7AcAXatqrFM"                                        
Traceback (most recent call last):
  File "/home/username/.local/bin/ciphey", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/ciphey.py", line 263, in main
    result = decrypt(config, kwargs["text"])
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/ciphey.py", line 32, in decrypt
    res: Optional[iface.SearchResult] = config.objs["searcher"].search(ctext)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 281, in search
    self.recursive_expand(node)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Searchers/ausearch.py", line 202, in expand_decodings
    res = inst(val)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/iface/_modules.py", line 186, in __call__
    return self.decode(*args)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/basemods/Decoders/atbash.py", line 29, in decode
    return fix_case(result, ctext)
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/common.py", line 15, in fix_case
    [
  File "/home/username/.local/lib/python3.9/site-packages/ciphey/common.py", line 16, in <listcomp>
    target[i].upper() if base[i].isupper() else target[i]
IndexError: string index out of range

**Comment by LPoeppel** [comment] 2021-11-21 19:02
Can be solved by adressing file common.py,
[line 17](https://github.com/Ciphey/Ciphey/blob/4e5cc80a3cfdd5361ddb2d99322ed9b3ba54dc90/ciphey/common.py#L17)
and
[line 23](https://github.com/Ciphey/Ciphey/blob/4e5cc80a3cfdd5361ddb2d99322ed9b3ba54dc90/ciphey/common.py#L23)
changing 
`range(len(target)) `
to
`range(len(target)-1)`

**Comment by SkeletalDemise** [comment] 2021-12-21 19:38
That's weird because I can't reproduce that. It works fine for me:
```
ciphey -t "56inrkS7AcAXatqrFM"
Possible plaintext: 'time\n00:10:51' (y/N): y
╭────────────────────────────╮
│ Formats used:              │
│    base58_bitcoin          │
│    reversePlaintext: "time │
│ 00:10:51"                  │
╰────────────────────────────╯
```
I'm curious, can you reproduce the bug using Python 3.8?

**Comment by Kozenomenon** [comment] 2022-02-07 14:31
Reproduced with 3.8. 

Windows 10
Python 3.8.3
Just installed latest ciphy. 

```
C:\Python38>python --version
Python 3.8.3

C:\Python38>python -m pip show ciphey cipheycore cipheydists
Name: ciphey
Version: 5.14.0
Summary: Automated Decryption Tool
Home-page:
Author: Autumn
Author-email: autumn@skerritt.blog
License: MIT
Location: c:\python38\lib\site-packages
Requires: appdirs, base58, base91, cipheycore, cipheydists, click, flake8, loguru, mock, pybase62, pylint, pywhat, pyyaml, rich
Required-by:
---
Name: cipheycore
Version: 0.3.2
Summary:
Home-page:
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License:
Location: c:\python38\lib\site-packages
Requires:
Required-by: ciphey
---
Name: cipheydists
Version: 0.3.35
Summary: A collection of distributions, character sets and dictionaries for use in ciphey
Home-page:
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License:
Location: c:\python38\lib\site-packages
Requires:
Required-by: ciphey

C:\Python38>python -m ciphy -t "56inrkS7AcAXatqrFM"
Traceback (most recent call last):
  File "C:\Python38\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python38\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python38\ciphy.py", line 3, in <module>
    main()
  File "C:\Python38\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "C:\Python38\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python38\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Python38\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "C:\Python38\lib\site-packages\ciphey\ciphey.py", line 263, in main
    result = decrypt(config, kwargs["text"])
  File "C:\Python38\lib\site-packages\ciphey\ciphey.py", line 32, in decrypt
    res: Optional[iface.SearchResult] = config.objs["searcher"].search(ctext)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 281, in search
    self.recursive_expand(node)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 213, in expand_decodings
    self.recursive_expand(new_node, False)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 221, in recursive_expand
    self.expand_decodings(node)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Searchers\ausearch.py", line 202, in expand_decodings
    res = inst(val)
  File "C:\Python38\lib\site-packages\ciphey\iface\_modules.py", line 186, in __call__
    return self.decode(*args)
  File "C:\Python38\lib\site-packages\ciphey\basemods\Decoders\atbash.py", line 29, in decode
    return fix_case(result, ctext)
  File "C:\Python38\lib\site-packages\ciphey\common.py", line 15, in fix_case
    [
  File "C:\Python38\lib\site-packages\ciphey\common.py", line 16, in <listcomp>
    target[i].upper() if base[i].isupper() else target[i]
IndexError: string index out of range
```

**Comment by SkeletalDemise** [comment] 2022-11-26 08:39
Closing this because I still can't produce it. As for the logs, running ciphey like `python -m ciphey` isn't recommended and that's not the latest version of Python 3.8. If someone can reproduce this using the latest Windows 10, latest Python 3.8, and current Ciphey then post your logs. Make sure to run it like this: `ciphey -t "56inrkS7AcAXatqrFM"`

**Closed by SkeletalDemise** 2022-11-26 08:39 UTC
Labels: bug
