### ISSUE TITLE
Print encrypted format when disable the human checker

### ISSUE THREAD

**Issue by tumuyan** [Ciphey/Ciphey#760] opened 2022-11-29 17:46 UTC
### Problem:
If I disable the human checker, it won't print the encrypted format. 
![image](https://user-images.githubusercontent.com/3126801/204603022-1e7bb27a-6c62-464a-b99c-bb6924828fbe.png)

### Solution:
print result without human checker, also print the format.
Also. if I use these python code, how to ger the format?

```
from ciphey import decrypt
from ciphey.iface import Config

text ="SGVsbG8gbXkgbmFtZSBpcyBiZWUgYW5kIEkgbGlrZSBkb2cgYW5kIGFwcGxlIGFuZCB0cmVl"
result = decrypt(
        Config().library_default().complete_config(),
        text
    )
print(result)
```

**Comment by tumuyan** [comment] 2022-12-06 11:07
@Veeeetzzzz 

result is a str so these code got these error. and I want get the encrypted format, not the decrypted_text 

```

AttributeError                            Traceback (most recent call last)
[<ipython-input-8-6162a387eddc>](https://localhost:8080/#) in <module>
      9 )
     10 
---> 11 decrypted_text = result.get_plaintext()
     12 
     13 print(decrypted_text)

AttributeError: 'str' object has no attribute 'get_plaintext'
```

**Comment by Veeeetzzzz** [comment] 2022-12-19 17:28
Sorry, I just realized I missed the first part of your post. It would probably be prudent to figure out why the issue is happening. 

From what I understand if you disable the human checker, the library will not discard the decrypted text even if it does not make sense, and will return it as the result. This means that if you disable the human checker and the decrypted text does not make sense, you will not be able to get the encrypted format of the text.

It sounds like intended functionality.

**Comment by SkeletalDemise** [comment] 2022-12-29 16:52
Hello, closing this because it's intended. Disabling the human checker will only return the first result that Ciphey finds. The library doesn't return the formats used, only the plaintext.

**Closed by SkeletalDemise** 2022-12-29 16:52 UTC
Labels: enhancement
