### ISSUE TITLE
Ciphey Failed To Crack!

### ISSUE THREAD

**Issue by DarshanBhoi** [Ciphey/Ciphey#289] opened 2020-08-25 03:06 UTC
**Describe the bug**
When I tried to decrypt the encoded string with Ciphey, it will try to crack it and in the end, it is unable to crack it and I got the output saying **"Failed to crack"**.

**To Reproduce**
1. What input did you use?
Ans. I'm trying to decode the string "Ecgudfxq_EcGmP". This is the input: "Ecgudfxq_EcGmP"
2. What flags / arguments did you use?
Ans. I used the "-t" flag/argument. So this is the input command: `ciphey -t "Ecgudfxq_EcGmP"`

**Verbose Output**
After running Ciphey with `ciphey -vvv` and the result is here in this file: 
[trace.log](https://github.com/Ciphey/Ciphey/files/5121058/trace.log)

**Expected behavior**
The encoded strings seem to be encoded using the substitution type (caesar)cipher, probably ROT14. So, Ciphey should easily decode it and we should have got the plain text back. But It was failed to crack the encoded string.  

**Screenshots**
![Screenshot](https://user-images.githubusercontent.com/70128281/91116291-06938e00-e65a-11ea-8f55-277a2ba7d979.png)

**Versions:**
 - OS/Distro: Kali Linux 2020.2
 - Python version: Python 3.8.3
 - Ciphey versions: 
Name: ciphey                               
Version: 5.2.0                             
Summary: Automated Decryption Tool         
Home-page: None                            
Author: Brandon                            
Author-email: brandon@skerritt.blog        
License: MIT                               
Location: /home/USER/.local/lib/python3.8/site-packages
Requires: flake8, yaspin, cipheydists, appdirs, base58, pylint, pyyaml, click, click-spinner, cipheycore, loguru, pybase62, rich
Required-by: 
Name: cipheycore
Version: 0.2.9
Summary: 
Home-page: None
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License: None
Location: /home/USER/.local/lib/python3.8/site-packages
Requires: 
Required-by: ciphey
Name: cipheydists
Version: 0.3.19
Summary: A collection of distributions, character sets and dictionaries for use in ciphey
Home-page: None
Author: Cyclic3
Author-email: cyclic3.git@gmail.com
License: None
Location: /home/USER/.local/lib/python3.8/site-packages
Requires: 
Required-by: ciphey

**Additional context**
Thanks for providing such a great tool. Please fix the issue and make it better. Looking forward to using it in the future.

**Comment by lukasgabriel** [comment] 2020-08-25 10:58
@all-contributors please add @DarshanBhoi  for bug

**Comment by Cyclic3** [comment] 2020-08-25 11:15
As discussed in the discord, this is *sort of* intended behaviour, since this is clearly not standard english text, a flag, or JSON. The checks that prevent this from being decoded can be bypassed with this (assuming you have a crib of `squad`):

```
ciphey -t "Ecgudfxq_EcGmP" -p caesar.p_value=-1 -C regex -p regex.regex=(?i)squad
```

To break this rather cryptic command down:

| Flags |  Description |
| -| -|
| `-t  "Ecgudfxq_EcGmP"` | Your ciphertext |
| `-p caesar.p_value=-1` | Allows any candidates that have more than a -100% chance to be used (i.e. all of them) |
| `-C regex  -p regex.regex=(?i)squad` | Use the regex checker with the case-insensitive crib `squad` |

**Comment by Cyclic3** [comment] 2020-08-25 12:48
On closer inspection, it appears that this is actually a symptom of #291. This may work after that is fixed

**Comment by SkeletalDemise** [comment] 2020-10-16 07:55
I am closing this issue because it's solved. Currently running `ciphey -t "Ecgudfxq_EcGmP"` works for me, without using regex. It gets decrypted by the Affine cracker (this is because Affine with a = 1 is the equivalent of a Caesar cipher) and then the underscore gets converted to a space by the leetspeak decoder.

**Closed by SkeletalDemise** 2020-10-16 07:55 UTC
Labels: bug, good first issue
