### ISSUE TITLE
an Encoding Error on gbk

### ISSUE THREAD

**Issue by Res01utionary** [Ciphey/Ciphey#753] opened 2022-09-20 01:06 UTC
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [y] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
When using ciphey, my cmd report an error.
"'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence"
**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
anything
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Windows 10
 - Python version: python 3.7.8
 - Ciphey versions:  5.14.0
 - Did you use Docker?
no
**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)
```
2022-09-20 09:04:58.783 | DEBUG    | ciphey.iface._config:update_log_level:174 - Verbosity set to level 3 (TRACE)
2022-09-20 09:04:58.784 | DEBUG    | ciphey.ciphey:main:199 - Opened config file at C:\Users\2eus\AppData\Local\ciphey\ciphey\config.yml
2022-09-20 09:04:58.785 | TRACE    | ciphey.ciphey:main:200 - Got cmdline args {'verbose': 3, 'text_stdin': None, 'text': None, 'quiet': None, 'greppable': None, 'checker': None, 'config': None, 'wordlist': None, 'param': (), 'list_params': None, 'searcher': None, 'bytes': None, 'default_dist': None, 'module': (), 'appdirs': False, 'file': None}
2022-09-20 09:04:58.785 | DEBUG    | ciphey.iface._config:load_modules:184 - Loaded modules ['any', 'brandon', 'jsonchecker', 'humanchecker', 'regex', 'regexlist', 'what', 'ezcheck', 'xandy', 'affine', 'ascii_shift', 'caesar', 'rot47', 'soundex', 'vigenere', 'xorsingle', 'xorcrypt', 'atbash', 'base58_bitcoin', 'base58_ripple', 'base62', 'base69', 'base91', 'base16', 'base32', 'base64', 'base85', 'ascii85', 'baudot', 'binary', 'braille', 'brainfuck', 'decimal', 'galactic', 'gzip', 'hexadecimal', 'leetspeak', 'morse_code', 'multi_tap', 'octal', 'reverse', 'tap_code', 'utf8', 'url', 'uuencode', 'cipheydists', 'json', 'csv', 'ausearch']
2022-09-20 09:04:58.787 | TRACE    | ciphey.iface._config:load_objs:130 - Registry is [<class 'ciphey.basemods.Checkers.any.Any'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>, <class 'ciphey.iface._modules.Checker.convert.<locals>.PolyWrapperClass'>]
Traceback (most recent call last):
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\Scripts\ciphey.exe\__main__.py", line 7, in <module>
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\click\core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\click\core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\click\core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\ciphey.py", line 222, in main
    config.complete_config()
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_config.py", line 189, in complete_config
    self.load_objs()
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_config.py", line 132, in load_objs
    _fwd.registry.get_named(self.checker, PolymorphicChecker)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\basemods\Checkers\ezcheck.py", line 46, in __init__
    self.checkers.append(config(What))
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_config.py", line 102, in __call__
    return self.instantiate(t)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_config.py", line 97, in instantiate
    ret = t(self)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\iface\_modules.py", line 153, in __init__
    self._base = cls(config)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\ciphey\basemods\Checkers\what.py", line 59, in __init__
    self.id = identifier.Identifier()
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pywhat\identifier.py", line 10, in __init__
    self.regex_id = RegexIdentifier()
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\site-packages\pywhat\regex_identifier.py", line 11, in __init__
    self.regexes = json.load(myfile)
  File "D:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\json\__init__.py", line 293, in load
    return loads(fp.read(),
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 695: illegal multibyte sequence
```
**To Reproduce**
1. What input did you use?
2. What flags / arguments did you use?
ciphey -t "GEZDG==="
**Expected behavior**
just decode
**Any other information?**

**Comment by SkeletalDemise** [comment] 2022-09-29 10:13
Closing this because it's a duplicate of #675. The bug was fixed in pyWhat, you need to update it.

**Closed by SkeletalDemise** 2022-09-29 10:13 UTC
Labels: bug
