### ISSUE TITLE
cipheycore error

### ISSUE THREAD

**Issue by jepunband** [Ciphey/Ciphey#508] opened 2020-10-20 16:23 UTC
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [* ] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)
Yes.

**Describe the bug**

ERROR: Could not find a version that satisfies the requirement cipheycore<0.4.0,>=0.3.1 (from ciphey) (from versions: 0.0.1)
ERROR: No matching distribution found for cipheycore<0.4.0,>=0.3.1 (from ciphey)

**Comment by TBO9IMAMKA234** [comment] 2020-10-30 16:40
I solved this problem by installing 64 bit Python.
If you have a Windows operating system, of course

**Comment by smarek** [comment] 2020-11-28 18:05
For Linux, this might be because of outdated PIP tool, upgrade pip3 first, then install ciphey
```
python3 -m pip install pip --upgrade
python3 -m pip install ciphey --upgrade
```

**Comment by SkeletalDemise** [comment] 2021-01-03 00:05
I'm closing this issue because you didn't fill out the full issue template so we don't know what system you're on and what versions. This error is usually caused by not using 64 bit Python and/or not using Python 3.7 or 3.8.

**Closed by SkeletalDemise** 2021-01-03 00:05 UTC
Labels: bug
