### ISSUE TITLE
Morse Code being mistaken as plaintext, brainfuck and ascii_shift

### ISSUE THREAD

**Issue by GalaxyLinus** [Ciphey/Ciphey#719] opened 2021-12-27 15:49 UTC
**⚠️IMPORTANT⚠️ if you do not fill this out, we will automatically delete your issue. We will not help anyone that cannot fill out this template.**

- [x] Have you read our [Wiki page "Common Issues & Their Solutions"?](https://github.com/Ciphey/Ciphey/wiki/Common-Issues-&-Their-Solutions)

**Describe the bug**
Entering Morse code into ciphey isn't detected

**Plaintext**
**⚠️IMPORTANT⚠️ The below code is non-negotiable for "Ciphey didn't decrypt...." problems. If you do not tell us your plaintext, we will not help you.** 

```
HELLO WORLD
```
**Version**
**⚠️IMPORTANT⚠️ We need this information because different environments will induce different bugs in Ciphey**
 - OS/Distro: Windows 10 latest
 - Python version: Python 3.8.5
 - Ciphey versions: 5.14.0
 - Did you use Docker? nope, good ol pip

**Verbose Output**
**⚠️IMPORTANT⚠️ Verbose output will tell us why it's not working the way we expected it to be.**
Run Ciphey with `ciphey -vvv` and paste the results into [Pastebin.com](https://pastebin.com) or a [GitHub Gist](https://gist.github.com/)

```
2021-12-27 16:45:05.175 | TRACE    | ciphey.basemods.Decoders.morse_code:decode:19 - Attempting Morse code decoder
2021-12-27 16:45:05.175 | TRACE    | ciphey.basemods.Decoders.morse_code:decode:31 - Non-morse char 'q' found
```

**To Reproduce**
1. What input did you use? ".... . .-.. .-.. ---  .-- --- .-. .-.. -.."
2. What flags / arguments did you use?
```
ciphey -t ".... . .-.. .-.. ---  .-- --- .-. .-.. -.."
Possible plaintext: '::::::ÿÿÿþþûöõõôôóó' (y/N): N
Possible plaintext: '::::::ÿÿÿþþûöõõôôóó' (y/N): N
Possible plaintext: '::::::ÿÿÿþþûöõõôôóó' (y/N): 
```
**Expected behavior**
Output: Hello World

**Any other information?**

**Comment by SkeletalDemise** [comment] 2022-01-24 09:31
Hello I'm closing this because it's not a bug. Your morse code isn't correct. It should be `ciphey -t ".... . .-.. .-.. ---/.-- --- .-. .-.. -.."`
You were missing the word delimiter.

**Closed by SkeletalDemise** 2022-01-24 09:31 UTC
Labels: bug
