### ISSUE TITLE
Freezes at xorcrypt while decoding MD5

### ISSUE THREAD

**Issue by An0n3m0us** [Ciphey/Ciphey#710] opened 2021-11-03 21:27 UTC
(Similar to https://github.com/Ciphey/Ciphey/issues/300#issuecomment-750924776)

**Describe the bug**
Ciphey freezes when decoding various types of formats (e.g with MD5)
Tested on my own system (info mentioned below), on a Docker (ubuntu-xenial-amd64 - Python 3.7), on a fresh Live system (Ubuntu 20.04 with Python3.8) and on a Kali Linux VMWare machine (Python 3.9)
All fail the same way, which is to completely freeze and not respond to any keyboard events.

**Plaintext**

```
098f6bcd4621d373cade4e832627b4f6
```
**Version**
 - OS/Distro: Ubuntu 16.04
 - Python version: Python 3.8
 - Ciphey versions: (ciphey 5.14.0) (cipheycore 0.3.2) (cipheydists 0.3.34)
 - Did you use Docker? No

**Verbose Output**
(From a run on my system)
```
DEBUG    | ciphey.basemods.Crackers.xor_single:attemptCrack:39 - Trying xor single cipher
TRACE    | ciphey.basemods.Crackers.xor_single:attemptCrack:42 - Beginning cipheycore simple analysis
TRACE    | ciphey.basemods.Crackers.xor_single:attemptCrack:43 - b'\x00UE\xc0t\x87\x92\xcc\x06F\xb6\x04\n\xbd\xaa`\r\xe9\xca\x95\x12\xbe\xab\xdc\x7f'
TRACE    | ciphey.basemods.Crackers.xor_single:attemptCrack:51 - Beginning cipheycore::xor_single
DEBUG    | ciphey.basemods.Crackers.xor_single:attemptCrack:57 - XOR single returned 0 candidates
TRACE    | ciphey.basemods.Crackers.xor_single:attemptCrack:66 - []
DEBUG    | ciphey.basemods.Searchers.ausearch:search:256 - At depth 1
TRACE    | ciphey.basemods.Searchers.ausearch:search:262 - 1 remaining on this level
TRACE    | ciphey.basemods.Searchers.ausearch:search:265 - Weight is currently 0.02 when we pick xorcrypt with depth 1
DEBUG    | ciphey.basemods.Crackers.xorcrypt:attemptCrack:78 - Trying xorcrypt cipher on b'AFVFwHSHkswGRrYECr2qYA3pypUSvqvcfw=='
TRACE    | ciphey.basemods.Crackers.xorcrypt:attemptCrack:97 - Got possible length 1
DEBUG    | ciphey.basemods.Searchers.ausearch:search:256 - At depth 2
TRACE    | ciphey.basemods.Searchers.ausearch:search:262 - 8800 remaining on this level
```

**To Reproduce**
`ciphey -t "098f6bcd4621d373cade4e832627b4f6" -vvv`

**Expected behavior**
Decodes MD5 hash as "test" or else fails and quits nicely rather than freezing then not listening to Ctrl+C events.

**Comment by SkeletalDemise** [comment] 2021-11-03 21:42
Hello. I'm going to close this because it's a duplicate of issue #605 where it's impossible to Ctrl+C to stop Ciphey after a while. This is a known bug from CipheyCore. Also Ciphey does not support hashes so it can't crack your hash.

**Closed by SkeletalDemise** 2021-11-03 21:42 UTC
Labels: bug
