### ISSUE TITLE
Base32 decryption and ROT13 decryption cannot occur at the same time

### ISSUE THREAD

**Issue by 2142156149** [Ciphey/Ciphey#758] opened 2022-11-19 13:53 UTC
Base32 decryption and ROT13 decryption cannot occur at the same time

**Comment by SkeletalDemise** [comment] 2022-11-26 08:26
Closing this because it's a duplicate of #606. There's a bug where Caesar doesn't work with encodings.

**Closed by SkeletalDemise** 2022-11-26 08:26 UTC
Labels: bug
