### ISSUE TITLE
can't  get the type of encryption 

### ISSUE THREAD

**Issue by a-gamer** [Ciphey/Ciphey#762] opened 2022-12-07 21:25 UTC
### Problem:
 i try to decrypt  code 
but it take long time it's  more than 40 hours now and still didn't  get any reply 

this is the code i try to decrypt 

0wZM0LrDP5vlXgKbTqbLqPMpzG0hcEMttA+kEaa0ezTF9eFrEiFQM41MinBANW0fuYK4OLoJDUa8gHQoacUE86IgsJNlVxFRm4VyT7YRzOZ8MZsMgEmUxyhehqGTxbUZpsvEPb9a22JioM9IdnE1c22QvlDrlFQjDKe/3iBcIkw9/834yOTEjDb19LVv4cADxp9BiWQ=

the decrypted code  must have phone  number  like 010 in it

**Comment by SkeletalDemise** [comment] 2022-12-29 16:58
Closing this because it's not a bug. If Ciphey can't crack something in over 5 minutes, it very likely can't. You can ask for help with specific ciphertexts in our Discord channel #coded-messages.
https://discord.gg/MfuMzEVjtK

**Closed by SkeletalDemise** 2022-12-29 16:58 UTC
Labels: enhancement
